### ISSUE TITLE
Possibility of adding a downloadable .deb file to Github releases?

### ISSUE THREAD

**Issue by PencilNotPen** [jkhsjdhjs/youtube-native-share#1]
Hi, and thanks very much for this!

I wondered if it would be possible to add a downloadable .deb file to the Github releases, so users don't need to download from a repo, which is a bit trickier (though not impossible) if they're not jailbroken. They can then bundle the .deb to the .ipa file themselves for non-jailbroken sideloading more easily.

Also, and I know you might not be interested in this, but would you consider making a similar tweak for Twitter/X, to remove tracking, replace x.com links with twitter.com links, and show the stock iOS share sheet? No worries if that's not something you'd use, it's just beyond my abilities to make...

Thanks for a great tweak!

**Comment by jkhsjdhjs** [comment]
Hey, I have now linked my repo in the about section of this repository. I also extended the repo to list all available debs, should be pretty intuitive.

Sorry to disappoint you, but I won't create a similar tweak for the Twitter app. I've never actively used it and stopped using it entirely once musk took over. You can however use an iOS shortcut to remove the twitter link tracking, there probably others that'll also replace x.com with twitter.com: https://routinehub.co/shortcut/5533/

However, I recommend switching to mastodon instead :handshake:

**Comment by PencilNotPen** [comment]
Hi, and thanks for responding.

Thanks for adding the repo link, I see it supports downloads via a browser without adding to a package manager, so that'll do nicely.

No worries about Twitter if you don't use it, and thanks for the Shortcut recommendation also.

Cheers
